import { defineField, defineType } from "sanity";

/**
 * Site-wide settings (mirrors the Strapi "site-setting" single type).
 * Enforced as a singleton: one document with a fixed _id of "siteSettings".
 * richtext fields (aboutOrigin, aboutOperatingInstinct) are kept as plain
 * markdown text so the app's react-markdown rendering keeps working.
 */
export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "copy", title: "Copy", default: true },
    { name: "home", title: "Homepage labels" },
    { name: "about", title: "About" },
    { name: "musings", title: "Musings page" },
    { name: "brands", title: "Brands pages" },
    { name: "skills", title: "Skills page" },
    { name: "work", title: "Case study pages" },
    { name: "contact", title: "Contact & socials" },
    { name: "media", title: "Media" },
    { name: "toggles", title: "Section toggles" },
  ],
  fields: [
    defineField({ name: "heroExperience", title: "Hero experience", type: "string", group: "copy" }),
    defineField({ name: "heroMarket", title: "Hero market", type: "string", group: "copy" }),
    defineField({ name: "heroStatus", title: "Hero focus", type: "string", group: "copy" }),
    defineField({ name: "contactCtaLabel", title: "Contact button label", type: "string", group: "copy" }),
    defineField({ name: "resumeCtaLabel", title: "Resume button label", type: "string", group: "copy" }),
    defineField({ name: "aboutCommunity", title: "Community and leadership", type: "text", rows: 6, group: "about" }),
    defineField({ name: "outcomeMetrics", title: "Outcome metrics", type: "array", group: "copy", of: [{ type: "object", fields: [
      defineField({ name: "label", title: "Label (include organisation)", type: "string", validation: r => r.required() }),
      defineField({ name: "value", title: "Value", type: "string", validation: r => r.required() }),
    ] }] }),
    // Home copy
    defineField({ name: "heroThesis", title: "Hero thesis", type: "text", rows: 4, group: "copy" }),
    defineField({ name: "problemLead", title: "Problem lead", type: "string", group: "copy", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "problemBody", title: "Problem body", type: "text", rows: 3, group: "copy" }),
    defineField({ name: "betLead", title: "Bet lead", type: "string", group: "copy", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "betBody", title: "Bet body", type: "text", rows: 4, group: "copy" }),
    defineField({ name: "outcomeLead", title: "Outcome lead", type: "string", group: "copy", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "signoffText", title: "Signoff text", type: "text", rows: 3, group: "copy", description: "Wrap words in [square brackets] to show them in grey." }),

    // About copy
    defineField({ name: "aboutHero", title: "About hero", type: "string", group: "about", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "aboutOrigin", title: "About origin", type: "text", rows: 5, group: "about" }),
    defineField({
      name: "aboutOperatingInstinct",
      title: "About operating instinct",
      type: "text",
      rows: 8,
      group: "about",
    }),

    // Homepage labels (fall back to content/site-copy.json when blank)
    defineField({ name: "homeEyebrow", title: "Eyebrow above your name", type: "string", group: "home" }),
    defineField({ name: "taglinePrefix", title: "Tagline start", type: "string", group: "home", description: "Shown before the rotating words, e.g. From bet →" }),
    defineField({ name: "taglineWords", title: "Tagline rotating words", type: "array", of: [{ type: "string" }], group: "home" }),
    defineField({ name: "exploreWorkLabel", title: "Explore my work label", type: "string", group: "home" }),
    defineField({ name: "problemTitle", title: "Section 01 title", type: "string", group: "home" }),
    defineField({ name: "betTitle", title: "Section 02 title", type: "string", group: "home" }),
    defineField({ name: "outcomeTitle", title: "Section 03 title", type: "string", group: "home" }),
    defineField({ name: "selectedWorkTitle", title: "Section 04 title", type: "string", group: "home" }),
    defineField({ name: "selectedWorkLead", title: "Section 04 lead line", type: "string", group: "home" }),
    defineField({ name: "discoveryTitle", title: "In discovery title", type: "string", group: "home" }),
    defineField({ name: "alsoBuiltTitle", title: "Section 05 title", type: "string", group: "home" }),
    defineField({ name: "alsoBuiltLead", title: "Section 05 lead line", type: "string", group: "home" }),
    defineField({ name: "workQshopTitle", title: "QShop group title", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workQshopLead", title: "QShop group lead line", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workYokeTitle", title: "Yoke group title", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workYokeLead", title: "Yoke group lead line", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workOrpheezTitle", title: "Orpheez group title", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workOrpheezLead", title: "Orpheez group lead line", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workFreelanceTitle", title: "Freelance group title", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workFreelanceLead", title: "Freelance group lead line", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workCommunityTitle", title: "Community group title", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workCommunityLead", title: "Community group lead line", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "workSideTitle", title: "Side projects group title", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "miracleKana", title: "Miracle card: name in Japanese", type: "string", group: "work" }),
    defineField({ name: "miracleName", title: "Miracle card: name", type: "string", group: "work" }),
    defineField({ name: "miracleLine", title: "Miracle card: line", type: "string", group: "work" }),
    defineField({ name: "miracleFoot", title: "Miracle card: small print", type: "string", group: "work" }),
    defineField({ name: "workSideLead", title: "Side projects group lead line", type: "string", group: "home", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "brandTeaserEyebrow", title: "Brand teaser eyebrow", type: "string", group: "home" }),
    defineField({ name: "brandTeaserTitle", title: "Brand teaser heading", type: "text", rows: 2, group: "home", description: "Use a new line for the second line (shown in italics / lighter)." }),
    defineField({ name: "brandTeaserBody", title: "Brand teaser text", type: "text", rows: 3, group: "home" }),
    defineField({ name: "brandTeaserLink", title: "Brand teaser link label", type: "string", group: "home" }),
    defineField({ name: "brandTeaserImageLabel", title: "Brand teaser image label", type: "string", group: "home" }),
    defineField({ name: "backgroundCtaLabel", title: "Background button label", type: "string", group: "home" }),

    // About page labels
    defineField({ name: "aboutEyebrow", title: "About eyebrow", type: "string", group: "about" }),
    defineField({ name: "aboutOriginTitle", title: "Section 00 title", type: "string", group: "about" }),
    defineField({ name: "aboutIdStatus", title: "ID card status", type: "string", group: "about" }),
    defineField({ name: "aboutInstinctTitle", title: "Section 01 title", type: "string", group: "about" }),
    defineField({ name: "aboutInstinctLead", title: "Section 01 lead line", type: "string", group: "about", description: "Wrap words in [square brackets] to show them in grey." }),
    defineField({ name: "aboutChangelogTitle", title: "Section 02 title", type: "string", group: "about" }),
    defineField({ name: "aboutCommunityTitle", title: "Section 03 title", type: "string", group: "about" }),

    // Musings page
    defineField({ name: "musingsEyebrow", title: "Eyebrow", type: "string", group: "musings" }),
    defineField({ name: "musingsTitle", title: "Heading", type: "text", rows: 2, group: "musings", description: "Use a new line for the second line (shown in italics / lighter)." }),
    defineField({ name: "musingsIntro", title: "Intro", type: "text", rows: 3, group: "musings", description: "Wrap a word in *asterisks* for italics." }),
    defineField({ name: "musingsNotebookTitle", title: "Section 01 title", type: "string", group: "musings" }),
    defineField({ name: "notifyLabel", title: "Get Notified button label", type: "string", group: "musings" }),
    defineField({ name: "notifyPostLabel", title: "Get Notified label (end of a post)", type: "string", group: "musings" }),
    defineField({ name: "notifyTitle", title: "Sign-up popup title", type: "string", group: "musings" }),
    defineField({ name: "notifyBody", title: "Sign-up popup text", type: "text", rows: 3, group: "musings" }),
    defineField({ name: "notifySuccess", title: "Sign-up success message", type: "text", rows: 2, group: "musings" }),
    defineField({ name: "notifyComingSoonTitle", title: "Coming-soon title (if sign-up is off)", type: "string", group: "musings" }),
    defineField({ name: "notifyComingSoonBody", title: "Coming-soon text (if sign-up is off)", type: "text", rows: 3, group: "musings" }),

    // Brands gallery + case pages
    defineField({ name: "brandsEyebrow", title: "Gallery eyebrow", type: "string", group: "brands" }),
    defineField({ name: "brandsCountLabel", title: "Gallery count label", type: "string", group: "brands", description: "Shown as <label> / 01—05; the numbers update automatically." }),
    defineField({ name: "brandsTitle", title: "Gallery heading", type: "text", rows: 2, group: "brands", description: "Use a new line for the second line (shown in italics / lighter)." }),
    defineField({ name: "brandsIntro", title: "Gallery intro", type: "text", rows: 2, group: "brands", description: "Each new line starts a new line on the page." }),
    defineField({ name: "brandsExploreLabel", title: "Explore button label", type: "string", group: "brands" }),
    defineField({ name: "brandsCollectionLabel", title: "Collection label", type: "string", group: "brands" }),
    defineField({ name: "brandsCollectionNote", title: "Collection note", type: "string", group: "brands" }),
    defineField({ name: "brandsNoteLabel", title: "Side note label", type: "string", group: "brands" }),
    defineField({ name: "brandsNoteTitle", title: "Side note heading", type: "text", rows: 3, group: "brands", description: "Each new line starts a new line; the last line is in italics." }),
    defineField({ name: "brandsNoteBody", title: "Side note text", type: "text", rows: 2, group: "brands" }),
    defineField({ name: "brandsAboutLabel", title: "About strip label", type: "string", group: "brands" }),
    defineField({ name: "brandsAboutBody", title: "About strip text", type: "text", rows: 3, group: "brands" }),
    defineField({ name: "brandsAboutLink", title: "About strip link label", type: "string", group: "brands" }),
    defineField({ name: "brandsFooterLabel", title: "Footer label", type: "string", group: "brands" }),
    defineField({ name: "brandsFooterTitle", title: "Footer heading", type: "text", rows: 2, group: "brands", description: "Use a new line for the second line (shown in italics / lighter)." }),
    defineField({ name: "brandsSignature", title: "Footer signature", type: "string", group: "brands" }),
    defineField({ name: "brandCaseSummaryLabel", title: "Case page: summary label", type: "string", group: "brands" }),
    defineField({ name: "brandContextLabel", title: "Case page: chapter 01 label", type: "string", group: "brands" }),
    defineField({ name: "brandContextTitle", title: "Case page: chapter 01 heading", type: "text", rows: 2, group: "brands", description: "Each new line starts a new line on the page." }),
    defineField({ name: "brandIdeaLabel", title: "Case page: chapter 02 label", type: "string", group: "brands" }),
    defineField({ name: "brandSystemLabel", title: "Case page: chapter 03 label", type: "string", group: "brands" }),
    defineField({ name: "brandTypeLabel", title: "Case page: typography panel label", type: "string", group: "brands" }),
    defineField({ name: "brandWorldLabel", title: "Case page: chapter 04 label", type: "string", group: "brands" }),
    defineField({ name: "brandWorldNote", title: "Case page: chapter 04 note", type: "string", group: "brands" }),
    defineField({ name: "brandWorldTitle", title: "Case page: chapter 04 heading", type: "text", rows: 2, group: "brands", description: "Use a new line for the second line (shown in italics / lighter)." }),
    defineField({ name: "brandDeliveryLabel", title: "Case page: chapter 05 label", type: "string", group: "brands" }),
    defineField({ name: "brandDeliveryTitle", title: "Case page: chapter 05 heading", type: "text", rows: 2, group: "brands", description: "Each new line starts a new line on the page." }),

    // Skills page (/skills)
    defineField({ name: "skillsEyebrow", title: "Eyebrow", type: "string", group: "skills" }),
    defineField({ name: "skillsTitle", title: "Heading", type: "text", rows: 2, description: "Use a new line for the second line (shown lighter).", group: "skills" }),
    defineField({ name: "skillsIntro", title: "Intro", type: "text", rows: 3, group: "skills" }),
    defineField({ name: "skillsLibraryTitle", title: "Section 01 title", type: "string", group: "skills" }),
    defineField({ name: "skillsDownloadLabel", title: "Download button label", type: "string", group: "skills" }),
    defineField({ name: "skillsDownloadAllLabel", title: "Download all button label", type: "string", group: "skills" }),
    defineField({ name: "skillsAllTitle", title: "Download all popup title", type: "string", group: "skills" }),
    defineField({ name: "skillsAllBody", title: "Download all popup text", type: "text", rows: 2, group: "skills" }),
    defineField({ name: "skillsThanks", title: "Thank-you line after a download", type: "text", rows: 2, group: "skills" }),
    defineField({ name: "skillsCookieText", title: "Cookie jar line", type: "string", group: "skills" }),
    defineField({ name: "skillsTipLabel", title: "Cookie jar button label", type: "string", group: "skills" }),
    defineField({ name: "skillsTipUrl", title: "Cookie jar link (tip page)", type: "string", description: "Paste your Paystack, Buy Me a Coffee or Ko-fi link. The cookie jar stays hidden while this is empty.", group: "skills" }),
    defineField({ name: "skillsNotifyLabel", title: "Get notified button label", type: "string", group: "skills" }),
    defineField({ name: "skillsNotifyTitle", title: "Sign-up popup title", type: "string", group: "skills" }),
    defineField({ name: "skillsNotifyBody", title: "Sign-up popup text", type: "text", rows: 3, group: "skills" }),
    defineField({ name: "skillsFooterLinkLabel", title: "Footer link (homepage and About)", type: "string", group: "skills" }),

    // Contact & socials
    defineField({ name: "fullName", title: "Full name", type: "string", group: "contact" }),
    defineField({ name: "jobTitle", title: "Job title", type: "string", group: "contact" }),
    defineField({ name: "email", title: "Email", type: "string", group: "contact" }),
    defineField({ name: "whatsapp", title: "WhatsApp", type: "string", group: "contact" }),
    defineField({ name: "githubUrl", title: "GitHub URL", type: "url", group: "contact" }),
    defineField({ name: "linkedinUrl", title: "LinkedIn URL", type: "url", group: "contact" }),
    defineField({ name: "contactMessage", title: "Contact message", type: "text", rows: 3, group: "contact" }),

    // Media
    defineField({
      name: "resume",
      title: "Resume (PDF)",
      type: "file",
      options: { accept: ".pdf" },
      group: "media",
    }),
    defineField({
      name: "profileImage",
      title: "Profile image",
      type: "image",
      options: { hotspot: true },
      group: "media",
    }),

    // Section toggles
    defineField({ name: "showProfileImage", title: "Show profile image", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showResume", title: "Show resume", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showProblem", title: "Show problem", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showBet", title: "Show bet", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showOutcome", title: "Show outcome", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showShipped", title: "Show shipped", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showAlsoBuilt", title: "Show also built", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showTimeline", title: "Show timeline", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showMusingsNav", title: "Show musings nav", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showSocials", title: "Show socials", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showContact", title: "Show contact", type: "boolean", initialValue: true, group: "toggles" }),
    defineField({ name: "showSignoff", title: "Show signoff", type: "boolean", initialValue: true, group: "toggles" }),
  ],
  preview: {
    prepare: () => ({ title: "Site Settings" }),
  },
});
